GET http://localhost:6969/orders

###

POST http://localhost:6969/orders HTTP/1.1
content-type: application/json

{
            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Y2NkYTViMjE1MDVkN2Y2MjdlNDVkYSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2OTE3NjgyMjEsImV4cCI6MTcyMzMwNDIyMX0.emtSwJSQAekKNsVSMjVRxn2xyzr4ocgEkgzKQF4mc8s",
            "order":{"songs": [
            "64ccda0c5fad016c15f71c3d",
            "64d2a2af3a54f70b2c2883f3",
            "64ccd9dd5fad016c15f71c39"
            ]
            }
}

###

DELETE http://localhost:6969/orders/
