GET http://localhost:6969/orders

###

POST http://localhost:6969/orders HTTP/1.1
content-type: application/json

{
            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ODMwZGM3NTU3NmExODdlMWFkNTk5MyIsImlhdCI6MTcwMzA4OTAzNiwiZXhwIjoxNzM0NjI1MDM2fQ.8mWFwjx_G8Hj1Q5-iUcUb-htcaLhdP0wVqiOaK1euJg",
            "order":{"songs": [
            "64e30d14fc68b9a5b37ba5bd",
            "64e30d2bfc68b9a5b37ba5be",
            "64e30d8cfc68b9a5b37ba5c0"
            ]
            }
}

###

DELETE http://localhost:6969/orders/
